"""'Init'

Revision ID: 0959eb0f8ee1
Revises: 290b363527b3
Create Date: 2024-03-21 17:28:06.846106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0959eb0f8ee1'
down_revision: Union[str, None] = '290b363527b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_login', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users_login', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_login', 'role')
    op.drop_column('users_login', 'active')
    # ### end Alembic commands ###
