"""add_post_public_id

Revision ID: 030a181bd7f7
Revises: 4b4ef644c7aa
Create Date: 2024-03-29 18:41:44.995522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030a181bd7f7'
down_revision: Union[str, None] = '4b4ef644c7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_public_id')
    # ### end Alembic commands ###
