"""add_qr_field

Revision ID: 1ffb53f08ba8
Revises: 030a181bd7f7
Create Date: 2024-03-29 19:22:35.803701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffb53f08ba8'
down_revision: Union[str, None] = '030a181bd7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('transformed_image_qr', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'transformed_image_qr')
    # ### end Alembic commands ###
