"""'Init'

Revision ID: 41f244125c36
Revises: 0959eb0f8ee1
Create Date: 2024-03-21 18:13:04.436348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f244125c36'
down_revision: Union[str, None] = '0959eb0f8ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_login', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users_login', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('users_login', 'crated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_login', sa.Column('crated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users_login', 'update_at')
    op.drop_column('users_login', 'created_at')
    # ### end Alembic commands ###
