"""upgrade_post_model

Revision ID: 4b4ef644c7aa
Revises: b87c411da1da
Create Date: 2024-03-29 18:12:18.147562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4ef644c7aa'
down_revision: Union[str, None] = 'b87c411da1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('transformed_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'transformed_image')
    # ### end Alembic commands ###
