"""update user model with foreign keys

Revision ID: 4b814f7cecf6
Revises: 539ba4b9e087
Create Date: 2024-03-26 11:09:09.605220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b814f7cecf6'
down_revision: Union[str, None] = '539ba4b9e087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
