"""add coments, posts, reletionships

Revision ID: f553642d0f16
Revises: 1a4c01a5e4f8
Create Date: 2024-03-25 19:32:28.376918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f553642d0f16'
down_revision: Union[str, None] = '1a4c01a5e4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
